#!/bin/bash
mysql -e "CREATE DATABASE TELCOMANAGER;"
mysql TELCOMANAGER -e "CREATE TABLE USER (
  USER_ID VARCHAR(255) NOT NULL,
  NAME_USER VARCHAR(255) NOT NULL,
  PRIMARY KEY (USER_ID));
  CREATE TABLE FILE (
    FILE_ID INT NOT NULL AUTO_INCREMENT,
    NAME_FILE VARCHAR(255) NOT NULL,
    ADRESS_FILE VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (FILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
    );"
